title: Ana Jovanovic PhD
logo: /assets/img/headshot_circle.png
description: I develop analytical tools to tackle industry challenges and curate strategies based on quantitative insights.
#show_downloads: false
theme: jekyll-theme-minimal
