title: Ana Jovanovic PhD
logo: /assets/img/headshot_circle.png
description: /n _I develop analytical tools to tackle industry challenges and curate strategies based on quantitative insights._
#show_downloads: false
theme: jekyll-theme-minimal
